# This file is part of pybhspc
# Copyright 2024-2025 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

site_name: pybhspc
nav:
  - Introduction: index.md
  - Getting Started: getting_started.py
  - API Reference:
    - bh_spc package: api.md
    - bh_spc.spcm module: api_spcm.md
  - Development: development.md
watch:
  - src
repo_url: https://github.com/marktsuchida/pybhspc
theme:
  name: material
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - include-markdown:
      start: <!-- begin-intro-docs -->
      end: <!-- end-intro-docs -->
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            show_source: false
            filters:
              - "!^_"            # Leave out dunders, sunders, and private.
              - "!^[A-Z0-9_]*$"  # Leave out enum members.
            docstring_style: numpy
            show_signature_annotations: true
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
